### ISSUE TITLE
Is it possible to change the background-color of the <CardElement/>

### ISSUE THREAD

**Issue by oneillsp96** [recurly/react-recurly#228]
Is it possible to change the background-color of the <CardElement/>? I didn't see a prop for that. The use case is our app uses dark mode

**Comment by OrionPro** [comment]
And how can I change these properties? And for example border or border radius . You can't change anything special there and it turns out that you can't make styling as you want according to the layout.

**Comment by drop-george** [comment]
@oneillsp96 did you figure this out?

**Comment by chrissrogers** [comment]
Hi! The background color of each Element is controllable through our custom css classes, which are outlined [here](https://recurly.com/developers/reference/recurly-js/#css-classes). Our `recurly.css` asset sets the default `background-color: #fff;`, but this can be overridden with your preferred color.

**Comment by OrionPro** [comment]
> Hi! The background color of each Element is controllable through our custom css classes, which are outlined [here](https://recurly.com/developers/reference/recurly-js/#css-classes). Our `recurly.css` asset sets the default `background-color: #fff;`, but this can be overridden with your preferred color.

Hi. Could you please provide a code example? No classes can change the background of the input inside the "Element" (CardNumberElement, CardMonthElement, CardYearElement, CardCvvElement). Moreover, there are also border, border-radius, and others. I couldn't change them to style the "input" as I need.

**Comment by chrissrogers** [comment]
The `<input>` itself in each Element is transparent, so the appearance can be dictated by the outer "container" HTMLDivElement, which we decorate with a few classes depending on the Element type and state.

Here's an example which would target a CardElement with a gray background and some border treatments:

```css
.recurly-element-card {
  background-color: gray;
  border-radius: 2px;
  border: 2px solid black;
}
```

However, if you're more interested in applying custom styles to the background and border of individual form controls inside of the CardElement, that isn't really possible for that Element. For that use-case, I recommend using the individual CardNumberElement, CardMonthElement, CardYearElement, and CardCvvElement, which are controllable in a similar manner:

```css
.recurly-element-number,
.recurly-element-month,
.recurly-element-year,
.recurly-element-cvv {
  background-color: gray;
  border-radius: 2px;
  border: 2px solid black;
}
```
